### ISSUE TITLE
Write Python script to read symbols.sel file. [$50]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#33]
Write a new script in Python 3 which will print the values from `symbols.sel` to the output.

Then print the known values to the output such as:

- symbol
- digits
- index
- group
- pointSize
- spread
- tickType
- time
- bid
- ask
- sessionHigh
- sessionLow
- bid_2
- ask_2
- etc.

Can be in any output format, but format of fields should match its type (ask/bid should print float and time should print time, etc.).

See: [`symbols.sel.h`](https://github.com/EA31337/MT-Formats/blob/master/symbols.sel.h)

Check some other code [examples](https://github.com/EA31337/MT-Formats/search?utf8=%E2%9C%93&q=symbols) for format details. Also [this one](https://github.com/nerr/nst_mbt/blob/master/experts/include/nst_public.mqh#L172).

Check these [symbols.sel files](https://github.com/FX31337/FX-BT-Scripts/files/190350/symbols.sel-examples.zip) as example.

**Comment by emmzett** [comment]
Hi. Let me provide a little contribution:
[SYMBOL_SELECTED.h.txt](https://github.com/FX31337/FX-BT-Scripts/files/170678/SYMBOL_SELECTED.h.txt)

**Comment by kenorb** [comment]
@emmzett Thank you, that's very useful. Do you have similar .h file for .raw format? If that's ok, I could include that in [MT-formats](https://github.com/EA31337/MT-formats) repo where I keep track different formats of MT, so we can write some Python scripts reading such formats.

**Comment by emmzett** [comment]
Yes, here are some more. All done by me and help of Birt.
[SYMBOL_GROUP.h.txt](https://github.com/FX31337/FX-BT-Scripts/files/174525/SYMBOL_GROUP.h.txt)
[SYMBOL.h.txt](https://github.com/FX31337/FX-BT-Scripts/files/174527/SYMBOL.h.txt)
[FXT_HEADER_405.h.txt](https://github.com/FX31337/FX-BT-Scripts/files/174528/FXT_HEADER_405.h.txt)

**Comment by emmzett** [comment]
If you want to work with your own tick files you can 
(a) use Birt's suite with a current build to patch the process at runtime (not free) or
(b) use an old build and patch it with Birt's patch script (free).

In both cases and assumed the terminal is disconnected you only need the symbols.sel file for profit conversion to the account currency. Otherwise only symbols.raw is needed.
Example: If I test SGDFX7 (that's a synthetic Singapure Dollar index that doesn't exist anywhere in the world but in my terminals symbols.raw) I set the account currency during testing to SGD and it works right away. If I would change it to something else I would get the error in the terminal log: "cannot convert margin currency" or similar. So, I can provide symbols.sel but I don't have to.

**Comment by emmzett** [comment]
@kenorb Had a look at the tick format.
[TICK.h.txt](https://github.com/FX31337/FX-BT-Scripts/files/174924/TICK.h.txt)
all the best

**Comment by kenorb** [comment]
@emmzett Thank you for the header files. I don't have problems with read-only files, it [works fine](EA31337/EA31337-Lite-Sets), the only problem which I am having that the platform reports spread 20, but in real it's 0 (Ask & Bid prices are exactly the same). The same happens when converting with Birt's scripts. However the real spread (Ask & Bid prices are different) applies only when the files aren't in read-only mode, but then the data seems to be tripled. So are you suggesting to use only HST files, then platform would generate tick data automatically?

**Comment by kenorb** [comment]
Fixed in PR #38

**Comment by kenorb** [comment]
@emmzett By any change, do you have any header format or some guesses for .srv format (server configuration files)?

**Comment by emmzett** [comment]
This is getting more difficult. Without reverse engineering you can only change the 1st ip address and port. A file can hold multiple entries, only the first one is in plain text. I use such a customized .srv file for my synthetic instruments.

The encrypted .ini-files and the .srv-files need to be decrypted but it's not easy. You need a good C++ developer for this. I never did it but I know the way to go:

You can start with build 225, that one is not copy protected and debugging is easy. You step through the application and put breakpoints on the file functions. Once the addresses are found you can go back from there and patch the decryption code away with no-ops, jumps etc. A smart way would be to patch the terminal to be able to read/write encrypted and decrypted files. Look at WinAPIOverride, that's an excellent piece of software:
http://jacquelin.potier.free.fr/winapioverride32/

With all the later builds it's getting more complicated because the terminal code is protected/obfuscated. It is still achievable and the encryption algorythm only changed marginally. However, if you do this or find somebody doing it for you do not publish it in a public place, like for example here at GitHub. MetaQuotes is desperately looking after reversing attempts. The moment somebody breaks their protection (which is not too hard) they will change the code (as they did a few times in the past with the broken server protocol) and your efforts will be wasted. So, keep the success for you. :-)

Imho you don't really need the .srv format for anything. With a modified file you can make for example the terminal act on online charts as it would do on offline charts. This way you can for example update an online chart from disk with ID_CHART_REFRESH wich doesn't work for regular online charts. Other than that I had no use for modified .srv files, at least until now.

**Comment by kenorb** [comment]
@emmzett Thanks for advise, really useful.

I've main 2 issues when testing with MT4: with lot step and spread values, these are very not stable and you never know how the test is going to be like.

Basically I'm expecting Lot step to be [0.1 for 4 digits](https://travis-ci.org/EA31337/FX-MT-VM/jobs/134022151#L3589), and [0.01 for 5 digits](https://travis-ci.org/EA31337/FX-MT-VM/jobs/134014765#L3591) brokers. These values seems to be connected to the server and stored in `accounts.ini` which is encoded. So as for workaround I've now two files: [`accounts-d4.ini`](https://github.com/EA31337/FX-MT-VM/blob/master/conf/accounts-d4.ini) to use for 4 digits, and [`accounts-d5.ini`](https://github.com/EA31337/FX-MT-VM/blob/master/conf/accounts-d5.ini) to use for 5 digits. In `accounts.ini` my account, server and password is encrypted, but this is necessary to set the  right Lot step and if I change [`Login=1809640`](https://github.com/EA31337/FX-MT-VM/blob/master/conf/mt4-tester.ini#L4) to something else, this stops working. This workaround is still not stable, as on some instances of MT4 the `accounts.ini` is wiped out even when I'm trying to copy the right one (ini file), so I assume MT4 needs also the right [`Server` value](https://github.com/EA31337/FX-MT-VM/blob/master/conf/mt4-tester.ini#L6) and the corresponding [`.srv` file](https://github.com/EA31337/FX-MT-VM/tree/master/conf/servers). This is all messed up. Maybe I don't need to read .srv, but definitely `accounts.ini` would be helpful to change the associated Lot step with the account.

Problem with Spread is that if I've backtest files read-only - [spread is 0 points](https://travis-ci.org/EA31337/FX-MT-VM/jobs/134032884#L3688) (always, doesn't matter if I change in fxt, ini, etc.). Only when files can be read-write, so platform can rewrite them [the spread is fine](https://travis-ci.org/EA31337/FX-MT-VM/jobs/134032883#L3593) (as set for the test). As the side-effect, the tick data is quadrupled (#54).

Have you come across similar problems? Haven't you noticed that the spread is always 0 when you've read-only files?

**Comment by emmzett** [comment]
Ah, now I understand what you meant last time. Yes, I agree. This setup is not stable. I follow a different approach. For testing I use another installation where I don't have any issues with different data coming from different connected brokers. I test always disconnected. The test installation is running on the same history folder as the online installation, this way price data is always up-to-date. Because I'm disconnected I can choose/set whatever spread I like, via the tester dialog or via a self generated tick file. As long as I do NOT choose 0 (zero spread) the terminal will not apply the current spread found in symbols.raw/symbols.sel. If you choose 0 the terminal will set the current spread sent by the broker. If you look in the symbols.raw file: a spread of non-zero means a fixed spread. A spread of 0 (zero) doesn't mean a zero spread but the current spread sent by the broker.

So, if I use the history folder and data of my broker and want to specify a low spread I select 1. That's more than realistic for a 5-digits broker (I don't use 4-digits brokers).

In general I generate history files by myself and write symbols.raw by myself. This way data is more accurate and spread is not an issue because I set a real 0 (zero) spread as the current spread in symbols.sel (bid = ask). Same for self-generated tick files.

Does this make sense to you?

**Comment by emmzett** [comment]
The last file reference needs to be corrected: "... as the current spread in symbols.raw (bid = ask)..."

**Comment by kenorb** [comment]
Re build 225, could you poke me on Skype by any chance (bronek_skype)? So I could probably drop you a line tomorrow. We could exchange few files, I can offer MQL CLI compiler which was removed recently from the site. And I may have an idea how to read srv.
